# Generated by Django 4.0.6 on 2022-07-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_status_project_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='value_proposition',
            field=models.TextField(max_length=2000),
        ),
    ]
