# Generated by Django 4.0.6 on 2022-07-14 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=400)),
                ('project', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
