# Generated by Django 4.0.6 on 2022-07-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
